version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=gfinance
      - POSTGRES_PASSWORD=gfinance
      - POSTGRES_DB=gfinance
      